### ISSUE TITLE
出现错误builtins.OSError

### ISSUE THREAD

**Issue by slen99** [alphardex/supertool#1]
Traceback (most recent call last):
  File "c:\users\surface\.virtualenvs\supertool-1iy4yzdh\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value

  File "C:\Users\surface\Desktop\supertool\supertool\__init__.py", line 11, in <module>
    from supertool.blueprints.main import bp as main_bp

  File "C:\Users\surface\Desktop\supertool\supertool\blueprints\main.py", line 3, in <module>
    from flask_weasyprint import HTML, CSS, render_pdf

  File "c:\users\surface\.virtualenvs\supertool-1iy4yzdh\lib\site-packages\flask_weasyprint\__init__.py", line 13, in <module>
    import weasyprint

  File "c:\users\surface\.virtualenvs\supertool-1iy4yzdh\lib\site-packages\weasyprint\__init__.py", line 393, in <module>
    from .css import preprocess_stylesheet  # noqa

  File "c:\users\surface\.virtualenvs\supertool-1iy4yzdh\lib\site-packages\weasyprint\css\__init__.py", line 26, in <module>
    from . import computed_values

  File "c:\users\surface\.virtualenvs\supertool-1iy4yzdh\lib\site-packages\weasyprint\css\computed_values.py", line 17, in <module>
    from .. import text

  File "c:\users\surface\.virtualenvs\supertool-1iy4yzdh\lib\site-packages\weasyprint\text.py", line 247, in <module>
    'libgobject-2.0.dylib')

  File "c:\users\surface\.virtualenvs\supertool-1iy4yzdh\lib\site-packages\weasyprint\text.py", line 243, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover

  File "c:\users\surface\.virtualenvs\supertool-1iy4yzdh\lib\site-packages\cffi\api.py", line 146, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)

  File "c:\users\surface\.virtualenvs\supertool-1iy4yzdh\lib\site-packages\cffi\api.py", line 828, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)

  File "c:\users\surface\.virtualenvs\supertool-1iy4yzdh\lib\site-packages\cffi\api.py", line 823, in _load_backend_lib
    raise OSError(msg)

OSError: cannot load library 'gobject-2.0': error 0x7e.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0'

**Comment by slen99** [comment]
无论使用pipenv运行还是自身环境直接运行均会报错
python版本为3.6.5

**Comment by alphardex** [comment]
这个问题我也碰到过，weasyprint的官方文档上说[需要安装GTK-Runtime](https://weasyprint.readthedocs.io/en/latest/install.html#step-4-install-the-gtk-libraries)
其实flask-weasyprint这个依赖去掉也罢，本repo里已经打印好了pdf版
